#!/bin/bash

# Update package lists
sudo apt-get update

# Install required dependencies
sudo apt-get install -y aptitude
sudo aptitude install -y build-essential cmake git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev python3-dev python3-numpy

# Install OpenCV
sudo aptitude install -y libopencv-dev python3-opencv

# Clone the RealSense GitHub repository
cd ~
git clone https://github.com/IntelRealSense/librealsense.git
cd librealsense

# Build and install the RealSense SDK with pyrealsense2
mkdir build && cd build
cmake .. -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7
make && sudo make install &

# Verify installation
echo "RealSense installation completed."

